### ISSUE TITLE
what is plotregion mean

### ISSUE THREAD

**Issue by merdan-9** [Schulze18/Explicit-MPC#1]
Hi

I run your algorithm1\example's code, but matlab said that 'plotregion' is undefined. 
How to fix this problem?
Thanks in advance.

Mario

**Comment by Schulze18** [comment]
Hi Mario,
Sorry for the late reply. 'plotregion' is a function that plots convex closed regions in 2D/3D. Here is the [link](https://www.mathworks.com/matlabcentral/fileexchange/9261-plot-2d-3d-region?focused=5143921&tab=function). 

I don't know which branch you cloned, but my suggest is to use the codes from 'binary_search_tree'.
